appId: fr.oceanerp.desktop
productName: OceanERP
directories:
  output: dist
files:
  - "src/**/*"
  - "assets/**/*"
  - "config/**/*"
  - "package.json"
asar: true
win:
  signAndEditExecutable: false
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: OceanERP
  uninstallDisplayName: OceanERP
