using Erp.Domain.Common;

namespace Erp.Domain.FutureModules;

// Phase 2/3 placeholders keep the ubiquitous language explicit without pretending
// that every workflow is production-complete in the MVP.
public sealed class Warehouse : AuditableEntity { public string Name { get; set; } = string.Empty; public string? AddressLine1 { get; set; } public string? AddressLine2 { get; set; } public string? PostalCode { get; set; } public string? City { get; set; } public string? Country { get; set; } public string? RepresentativeName { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public string? Notes { get; set; } }
public sealed class StockItem : AuditableEntity { public Guid ProductId { get; set; } public Guid WarehouseId { get; set; } public decimal QuantityOnHand { get; set; } public decimal QuantityReserved { get; set; } public decimal AlertThreshold { get; set; } }
public sealed class StockMovement : AuditableEntity { public Guid ProductId { get; set; } public Guid WarehouseId { get; set; } public decimal Quantity { get; set; } public string Type { get; set; } = "Adjustment"; public string Reason { get; set; } = string.Empty; public string? ReferenceModule { get; set; } public Guid? ReferenceId { get; set; } }
public sealed class SalesOrder : AuditableEntity { public string Number { get; set; } = string.Empty; public Guid CustomerId { get; set; } public Guid? WarehouseId { get; set; } public string Status { get; set; } = "Draft"; public string? ExternalStatusName { get; set; } public DateTimeOffset? OrderedAt { get; set; } public string? PaymentMethod { get; set; } public string? PaymentModule { get; set; } public decimal? PaidTotal { get; set; } public decimal? ProductsTotal { get; set; } public decimal? ShippingTotal { get; set; } public decimal? ShippingWeightKg { get; set; } public string? InvoiceReference { get; set; } public string? ShippingServiceName { get; set; } public string? ShippingCarrierName { get; set; } public string? ShippingTrackingNumber { get; set; } public string? ShippingAddressName { get; set; } public string? ShippingAddressLine1 { get; set; } public string? ShippingAddressLine2 { get; set; } public string? ShippingPostalCode { get; set; } public string? ShippingCity { get; set; } public string? ShippingCountry { get; set; } public string? ShippingPhone { get; set; } public string? ShippingEmail { get; set; } public DateTimeOffset? ConfirmedAt { get; set; } public DateTimeOffset? ShippedAt { get; set; } public DateTimeOffset? CompletedAt { get; set; } public DateTimeOffset? CancelledAt { get; set; } }
public sealed class SalesOrderLine : Entity { public Guid SalesOrderId { get; set; } public Guid? ProductId { get; set; } public string Description { get; set; } = string.Empty; public decimal Quantity { get; set; } public decimal UnitPrice { get; set; } }
public sealed class SalesOrderStatusHistory : Entity { public Guid SalesOrderId { get; set; } public string Status { get; set; } = string.Empty; public DateTimeOffset ChangedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Invoice : AuditableEntity { public string Number { get; set; } = string.Empty; public string Kind { get; set; } = "Invoice"; public Guid CustomerId { get; set; } public Guid? SalesOrderId { get; set; } public Guid? CreditOfInvoiceId { get; set; } public string Status { get; set; } = "Draft"; public DateOnly IssueDate { get; set; } = DateOnly.FromDateTime(DateTime.UtcNow); public DateOnly DueDate { get; set; } = DateOnly.FromDateTime(DateTime.UtcNow.AddDays(30)); public string FacturXProfile { get; set; } = "Basic"; }
public sealed class InvoiceLine : Entity { public Guid InvoiceId { get; set; } public string Description { get; set; } = string.Empty; public decimal Quantity { get; set; } public decimal UnitPrice { get; set; } }
public sealed class InvoicePayment : Entity { public Guid InvoiceId { get; set; } public decimal Amount { get; set; } public DateOnly PaidOn { get; set; } }
public sealed class InvoiceDocument : Entity { public Guid InvoiceId { get; set; } public string FileName { get; set; } = string.Empty; public string MimeType { get; set; } = string.Empty; public string StoragePath { get; set; } = string.Empty; public long Size { get; set; } public int Version { get; set; } = 1; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class InvoiceStatusHistory : Entity { public Guid InvoiceId { get; set; } public string Status { get; set; } = string.Empty; public DateTimeOffset ChangedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class Supplier : AuditableEntity { public string Name { get; set; } = string.Empty; }
public sealed class PurchaseOrder : AuditableEntity { public string Number { get; set; } = string.Empty; public Guid SupplierId { get; set; } public Guid? WarehouseId { get; set; } public string Status { get; set; } = "Draft"; public DateOnly? ExpectedAt { get; set; } public string? Comment { get; set; } public DateTimeOffset? OrderedAt { get; set; } public DateTimeOffset? ReceivedAt { get; set; } public DateTimeOffset? CancelledAt { get; set; } }
public sealed class PurchaseOrderLine : Entity { public Guid PurchaseOrderId { get; set; } public Guid? ProductId { get; set; } public string Description { get; set; } = string.Empty; public decimal Quantity { get; set; } public decimal UnitPrice { get; set; } public decimal VatRate { get; set; } = 20m; public decimal ReceivedQuantity { get; set; } }
public sealed class PurchaseOrderCharge : Entity { public Guid PurchaseOrderId { get; set; } public string Label { get; set; } = string.Empty; public decimal Amount { get; set; } public decimal VatRate { get; set; } = 20m; }
public sealed class SupplierInvoice : AuditableEntity { public string Number { get; set; } = string.Empty; public Guid SupplierId { get; set; } public decimal Total { get; set; } }
public sealed class GoodsReceipt : AuditableEntity { public string Number { get; set; } = string.Empty; public Guid PurchaseOrderId { get; set; } }
public sealed class AccountingEntry : AuditableEntity { public string JournalCode { get; set; } = string.Empty; public decimal Debit { get; set; } public decimal Credit { get; set; } }
public sealed class Payment : AuditableEntity { public decimal Amount { get; set; } public DateOnly PaymentDate { get; set; } }
public sealed class AccountJournal : AuditableEntity { public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; }
public sealed class ServiceTicket : AuditableEntity { public string Number { get; set; } = string.Empty; public Guid CustomerId { get; set; } public Guid? ProductId { get; set; } public Guid? SalesOrderId { get; set; } public Guid? AssignedUserId { get; set; } public string Subject { get; set; } = string.Empty; public string? Description { get; set; } public string Priority { get; set; } = "Normal"; public string Status { get; set; } = "Open"; }
public sealed class ServiceTicketMessage : Entity { public Guid ServiceTicketId { get; set; } public Guid? AuthorUserId { get; set; } public string? ExternalAuthorName { get; set; } public string? ExternalAuthorEmail { get; set; } public string Body { get; set; } = string.Empty; public bool IsInternal { get; set; } public Guid? AttachmentDriveItemId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ServiceTicketStatusHistory : Entity { public Guid ServiceTicketId { get; set; } public string Status { get; set; } = string.Empty; public string? Comment { get; set; } public Guid? ChangedByUserId { get; set; } public DateTimeOffset ChangedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ServiceTicketInitialResponder : Entity { public Guid UserId { get; set; } }
public sealed class ServiceTicketWatcher : Entity { public Guid ServiceTicketId { get; set; } public Guid UserId { get; set; } public DateTimeOffset AddedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ServiceTicketPublicLink : Entity { public Guid ServiceTicketId { get; set; } public string TokenHash { get; set; } = string.Empty; public DateTimeOffset ExpiresAt { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public Guid? CreatedByUserId { get; set; } public bool IsRevoked { get; set; } }
public sealed class MailServerSettings : AuditableEntity { public string SmtpHost { get; set; } = string.Empty; public int SmtpPort { get; set; } = 587; public string ImapHost { get; set; } = string.Empty; public int ImapPort { get; set; } = 993; public bool UseSsl { get; set; } = true; public bool ImapAutoSyncEnabled { get; set; } = true; public int ImapSyncIntervalMinutes { get; set; } = 5; public Guid? DefaultSystemMailAccountId { get; set; } }
public sealed class MailAccount : AuditableEntity { public string Email { get; set; } = string.Empty; public string? DisplayName { get; set; } public string? SignatureHtml { get; set; } public string SmtpHost { get; set; } = string.Empty; public int SmtpPort { get; set; } = 587; public string ImapHost { get; set; } = string.Empty; public int ImapPort { get; set; } = 993; public bool UseSsl { get; set; } = true; public string? UserName { get; set; } public string? PasswordSecretName { get; set; } public string? PasswordProtectedValue { get; set; } public bool IsActive { get; set; } = true; public ICollection<MailAccountAccess> Accesses { get; set; } = new List<MailAccountAccess>(); }
public sealed class MailAccountAccess : Entity { public Guid MailAccountId { get; set; } public Guid UserId { get; set; } }
public sealed class EmailMessage : AuditableEntity { public Guid? MailAccountId { get; set; } public string? ExternalMessageId { get; set; } public string Subject { get; set; } = string.Empty; public string From { get; set; } = string.Empty; public string To { get; set; } = string.Empty; public string? Cc { get; set; } public string? Bcc { get; set; } public string Body { get; set; } = string.Empty; public string Direction { get; set; } = "Outgoing"; public string Status { get; set; } = "Draft"; public bool IsRead { get; set; } public bool IsDeleted { get; set; } public string? ErrorMessage { get; set; } public DateTimeOffset? SentAt { get; set; } public DateTimeOffset? ReceivedAt { get; set; } public DateTimeOffset? DeletedAt { get; set; } }
public sealed class EmailAttachment : Entity { public Guid EmailMessageId { get; set; } public string FileName { get; set; } = string.Empty; public string MimeType { get; set; } = "application/octet-stream"; public long Size { get; set; } public string StoragePath { get; set; } = string.Empty; }
public sealed class EmailLink : Entity { public Guid EmailMessageId { get; set; } public string Module { get; set; } = string.Empty; public Guid EntityId { get; set; } }
public sealed class EmailTemplate : AuditableEntity { public string Name { get; set; } = string.Empty; public string Subject { get; set; } = string.Empty; public string Body { get; set; } = string.Empty; public bool IsActive { get; set; } = true; }
public sealed class EmailDistributionList : AuditableEntity { public string Name { get; set; } = string.Empty; public string? Description { get; set; } public bool IsActive { get; set; } = true; public ICollection<EmailDistributionListMember> Members { get; set; } = new List<EmailDistributionListMember>(); }
public sealed class EmailDistributionListMember : Entity { public Guid EmailDistributionListId { get; set; } public string? Name { get; set; } public string Email { get; set; } = string.Empty; }
public sealed class AiSettings : AuditableEntity { public bool IsEnabled { get; set; } public string Provider { get; set; } = "groq"; public string EndpointUrl { get; set; } = "https://api.groq.com/openai/v1"; public string Model { get; set; } = "llama-3.3-70b-versatile"; public string? ApiKeySecretName { get; set; } = "GROQ_API_KEY"; public string? ApiKeyProtectedValue { get; set; } public decimal Temperature { get; set; } = 0.2m; public int MaxTokens { get; set; } = 4096; public string? SystemPrompt { get; set; } }
public sealed class QuoteDocumentSettings : AuditableEntity { public string CompanyName { get; set; } = "OceanERP"; public string? AddressLine1 { get; set; } public string? AddressLine2 { get; set; } public string? PostalCode { get; set; } public string? City { get; set; } public string? Country { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public string? Website { get; set; } public string? VatNumber { get; set; } public string? Siret { get; set; } public string? LegalText { get; set; } public string? FooterText { get; set; } public string? LogoStoragePath { get; set; } public string? LogoFileName { get; set; } public string? LogoMimeType { get; set; } public long? LogoSize { get; set; } }
public sealed class CalendarEvent : AuditableEntity { public string Title { get; set; } = string.Empty; public string? Description { get; set; } public string? Location { get; set; } public DateTimeOffset StartsAt { get; set; } public DateTimeOffset EndsAt { get; set; } public bool IsPrivate { get; set; } }
public sealed class CalendarReminder : Entity { public Guid CalendarEventId { get; set; } public DateTimeOffset RemindAt { get; set; } public bool IsSent { get; set; } }
public sealed class CalendarEventLink : Entity { public Guid CalendarEventId { get; set; } public string Module { get; set; } = string.Empty; public Guid EntityId { get; set; } }
public sealed class CalendarParticipant : Entity { public Guid CalendarEventId { get; set; } public Guid? UserId { get; set; } public string? ExternalName { get; set; } public string? ExternalEmail { get; set; } public string Type { get; set; } = "Internal"; public string Status { get; set; } = "Invited"; public string? InviteTokenHash { get; set; } public DateTimeOffset? InviteSentAt { get; set; } public DateTimeOffset? RespondedAt { get; set; } }
public sealed class SignatureRequest : AuditableEntity { public Guid DriveItemId { get; set; } public string Title { get; set; } = string.Empty; public string Status { get; set; } = "Pending"; public DateTimeOffset ExpiresAt { get; set; } public DateTimeOffset? CompletedAt { get; set; } }
public sealed class SignatureRecipient : Entity { public Guid SignatureRequestId { get; set; } public string Email { get; set; } = string.Empty; public string? Name { get; set; } public string TokenHash { get; set; } = string.Empty; public string Status { get; set; } = "Pending"; public DateTimeOffset? SignedAt { get; set; } }
public sealed class SignatureOtp : Entity { public Guid SignatureRecipientId { get; set; } public string OtpHash { get; set; } = string.Empty; public DateTimeOffset ExpiresAt { get; set; } public DateTimeOffset? UsedAt { get; set; } }
public sealed class SignatureEvidence : Entity { public Guid SignatureRequestId { get; set; } public Guid? SignatureRecipientId { get; set; } public string Action { get; set; } = "Accepted"; public string DocumentSha256 { get; set; } = string.Empty; public bool ConditionsAccepted { get; set; } public string? SignatureMode { get; set; } public string? DrawnSignatureDataUrl { get; set; } public string? IpAddress { get; set; } public string? UserAgent { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class SignedDocument : Entity { public Guid SignatureRequestId { get; set; } public string FileName { get; set; } = string.Empty; public string MimeType { get; set; } = "application/pdf"; public long Size { get; set; } public string StoragePath { get; set; } = string.Empty; public string DocumentSha256 { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PrestashopConnection : AuditableEntity { public string ShopUrl { get; set; } = string.Empty; public string ApiKeySecretName { get; set; } = string.Empty; public string? ApiKeyProtectedValue { get; set; } public string? ColissimoLabelEndpointTemplate { get; set; } public string? ColissimoBridgeTokenProtectedValue { get; set; } public bool IsActive { get; set; } = true; public Guid? WarehouseId { get; set; } }
public sealed class PrestashopSyncLog : Entity { public Guid PrestashopConnectionId { get; set; } public string Status { get; set; } = string.Empty; public string Message { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? StartedAt { get; set; } public DateTimeOffset? CompletedAt { get; set; } }
public sealed class ExternalReference : Entity { public string Provider { get; set; } = string.Empty; public string ExternalId { get; set; } = string.Empty; public string Module { get; set; } = string.Empty; public Guid EntityId { get; set; } }
public sealed class ApiClient : AuditableEntity { public string Name { get; set; } = string.Empty; public bool IsActive { get; set; } = true; }
public sealed class ApiKey : Entity { public Guid ApiClientId { get; set; } public string KeyHash { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ApiRequestLog : Entity { public Guid? ApiClientId { get; set; } public string Path { get; set; } = string.Empty; public int StatusCode { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class FlowceanWorkspace : AuditableEntity { public string Slug { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public Guid? OwnerUserId { get; set; } public string DataJson { get; set; } = "{}"; public int Version { get; set; } = 1; public bool IsPersonal { get; set; } }
public sealed class FlowceanWorkspaceMember : AuditableEntity { public Guid FlowceanWorkspaceId { get; set; } public Guid UserId { get; set; } public string Role { get; set; } = "editor"; }
public sealed class FlowceanWorkspaceEvent : Entity { public Guid FlowceanWorkspaceId { get; set; } public Guid? ActorUserId { get; set; } public string EventType { get; set; } = "Saved"; public string PayloadJson { get; set; } = "{}"; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class MeetingRoom : AuditableEntity { public string Code { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public Guid? CalendarEventId { get; set; } public string? InviteToken { get; set; } public DateTimeOffset? ScheduledStartAt { get; set; } public DateTimeOffset LastActivityAt { get; set; } = DateTimeOffset.UtcNow; public bool IsLocked { get; set; } }
public sealed class MeetingParticipant : Entity { public Guid MeetingRoomId { get; set; } public Guid? UserId { get; set; } public string ClientId { get; set; } = string.Empty; public string DisplayName { get; set; } = string.Empty; public string SourceLanguage { get; set; } = "fr-FR"; public string TargetLanguage { get; set; } = "en-US"; public bool MicrophoneEnabled { get; set; } public bool CameraEnabled { get; set; } public bool ScreenEnabled { get; set; } public string ConnectionState { get; set; } = "Connected"; public DateTimeOffset JoinedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset LastSeenAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class MeetingSignal : Entity { public Guid MeetingRoomId { get; set; } public string SenderClientId { get; set; } = string.Empty; public string RecipientClientId { get; set; } = string.Empty; public string SignalType { get; set; } = string.Empty; public string PayloadJson { get; set; } = "{}"; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class MeetingTranscript : Entity { public Guid MeetingRoomId { get; set; } public Guid? UserId { get; set; } public string ClientId { get; set; } = string.Empty; public string SpeakerName { get; set; } = string.Empty; public string SourceLanguage { get; set; } = "fr-FR"; public string Text { get; set; } = string.Empty; public string? TranslatedText { get; set; } public bool IsFinal { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class MeetingChatMessage : Entity { public Guid MeetingRoomId { get; set; } public Guid? UserId { get; set; } public string ClientId { get; set; } = string.Empty; public string SenderName { get; set; } = string.Empty; public string Message { get; set; } = string.Empty; public string? FileName { get; set; } public string? FileMimeType { get; set; } public long? FileSize { get; set; } public string? FileStoragePath { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
